# Generated by Django 2.1 on 2018-11-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfeeder', '0002_auto_20181031_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petconsumptionaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
