# Generated by Django 2.1 on 2018-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfeeder', '0004_auto_20181121_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfeeder',
            name='setting_cup',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='petfeeder',
            name='setting_interval',
            field=models.FloatField(default=0),
        ),
    ]
